name: Test Github Actions

on: [push, pull_request]

env:
  NODE_VERSION: 12.x

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Environment Information
        run: npx envinfo

      - name: Echo Details
        run: echo "${{ github.event }}"
