name: Test Github Actions

on: 
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

env:
  NODE_VERSION: 12.x

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # - name: Setup Node.js ${{ env.NODE_VERSION }}
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: ${{ env.NODE_VERSION }}
      # - name: Environment Information
      #   run: npx envinfo
      # - name: Echo Details
      #   run: echo "${{ toJson(github) }}"

      - name: Hello world action step
        id: hello
        uses: roshanlas/test-slack-action@v1.1.3
        with:
          slack-token: ${{ secrets.SLACK_DDBOT_TOKEN }}
          slack-secret: ${{ secrets.SLACK_DDBOT_SECRET }}
          slack-channel-id: "${{ secrets.SLACK_DDBOT_CHANNEL }}"

      # - name: Get the output time
      #   run: echo "The time was ${{ steps.hello.outputs.time }}"
